"use client";
import {useEffect,useMemo,useRef} from "react";
import {AnimatePresence,motion} from "framer-motion";
const EASE=[.4,0,.2,1],TABS=[{id:"all",label:"ВСИЧКИ",tone:"all"},{id:"women",label:"ЖЕНИ",tone:"female"},{id:"men",label:"МЪЖЕ",tone:"male"}],cn=(...v)=>v.filter(Boolean).join(" ");
const XIcon=({className=""})=><svg viewBox="0 0 24 24" className={className} fill="none" aria-hidden="true"><path d="M7 7l10 10M17 7L7 17" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round"/></svg>;
function CloseButton({onClick}){return <button type="button" onClick={onClick} aria-label="Close" className="relative grid h-12 w-12 place-items-center rounded-[18px] border border-cyan-400/70 bg-[linear-gradient(180deg,rgba(6,16,24,.98),rgba(3,8,14,.98))] text-white/88 shadow-[0_18px_34px_rgba(0,0,0,.34),inset_0_1px_0_rgba(255,255,255,.07)] transition duration-200 hover:-translate-y-[1px] hover:border-cyan-300/95 hover:brightness-110"><span className="absolute inset-[1px] rounded-[17px] bg-[radial-gradient(90px_52px_at_30%_18%,rgba(255,255,255,.08),transparent_64%)]"/><span className="absolute inset-0 rounded-[18px] shadow-[inset_0_0_0_1px_rgba(0,255,210,.05)]"/><XIcon className="relative h-[18px] w-[18px]"/></button>}
function TabButton({active,label,tone,onClick}){const base=tone==="female"?"border-pink-400/45 text-pink-200/95 hover:border-pink-300/75":tone==="male"?"border-sky-400/45 text-sky-200/95 hover:border-sky-300/75":"border-cyan-400/45 text-white/82 hover:border-cyan-300/75";const activeCls=tone==="female"?"border-pink-300/90 bg-[linear-gradient(135deg,rgba(244,114,182,.34),rgba(80,7,36,.58))] text-white":tone==="male"?"border-sky-300/90 bg-[linear-gradient(135deg,rgba(56,189,248,.28),rgba(7,38,74,.60))] text-white":"border-cyan-300/95 bg-[linear-gradient(135deg,rgba(56,189,248,.92),rgba(8,47,73,.86))] text-white";return <button type="button" onClick={onClick} className={cn("group relative inline-flex h-[56px] min-w-[112px] items-center justify-center overflow-hidden rounded-full border bg-[linear-gradient(180deg,rgba(2,6,23,.78),rgba(15,23,42,.48))] px-5 font-black tracking-[.06em] transition-all duration-200",base,active&&cn("shadow-[inset_0_1px_0_rgba(255,255,255,.08),0_0_0_1px_rgba(255,255,255,.02)]",activeCls),!active&&"hover:-translate-y-[1px]")}><span className="relative z-[1]">{label}</span><span className={cn("absolute bottom-[10px] left-[18px] right-[18px] h-[2px] rounded-full transition duration-200",active?"bg-current shadow-[0_0_14px_currentColor]":"bg-transparent group-hover:bg-current group-hover:shadow-[0_0_14px_currentColor]")}/></button>}
function SearchField({value,onChange,inputRef}){return <label className="group relative flex h-[56px] items-center rounded-full border border-cyan-400/35 bg-[radial-gradient(circle_at_0_0,rgba(56,189,248,.14),transparent_46%),linear-gradient(180deg,rgba(15,23,42,.86),rgba(2,6,23,.72))] transition duration-200 hover:border-cyan-300/60 focus-within:border-cyan-300/90 focus-within:shadow-[0_0_0_4px_rgba(56,189,248,.12)]"><span className="pointer-events-none absolute left-5 text-[1rem] font-black text-cyan-200/85">⌕</span><input ref={inputRef} className="h-full w-full bg-transparent px-[18px] pl-12 text-[1rem] font-extrabold tracking-[.02em] text-white outline-none placeholder:text-slate-400/85" value={value} onChange={e=>onChange(e.target.value)} placeholder="Search..." autoComplete="off"/></label>}
function EmptyState({loading}){return <div className="flex min-h-[180px] items-center justify-center rounded-[24px] border border-dashed border-white/10 bg-[rgba(2,6,23,.22)] px-4 text-center text-[.94rem] font-bold text-white/50">{loading?"Зареждане...":"Няма намерени крупиета"}</div>}
function PersonCard({item,onPick}){const female=item.gender==="FEMALE",tones=female?"border-pink-400/28 hover:border-pink-300/70 hover:bg-[linear-gradient(180deg,rgba(59,7,32,.42),rgba(2,6,23,.92))] text-pink-50":"border-sky-400/28 hover:border-sky-300/70 hover:bg-[linear-gradient(180deg,rgba(7,38,74,.44),rgba(2,6,23,.92))] text-sky-50";return <motion.button whileTap={{scale:.988}} type="button" onClick={onPick} className={cn("group relative flex min-h-[58px] items-center justify-between gap-4 overflow-hidden rounded-[18px] border bg-[linear-gradient(180deg,rgba(2,6,23,.92),rgba(5,10,25,.88))] px-4 text-left font-black transition duration-150 hover:-translate-y-[1px] hover:shadow-[0_12px_26px_rgba(0,0,0,.22)]",tones)}><span className="absolute inset-0 bg-[radial-gradient(240px_110px_at_20%_10%,rgba(255,255,255,.05),transparent_64%)] opacity-80"/><span className="relative truncate text-[.98rem] uppercase tracking-[.04em]">{item.nickname||"—"}</span><span className="relative text-[.72rem] uppercase tracking-[.18em] text-white/46 transition group-hover:text-white">Избери</span></motion.button>}
function Column({label,tone,items,loading,onPick}){const female=tone==="female";return <section className={cn("relative flex min-h-0 flex-col overflow-hidden rounded-[26px] border p-4 shadow-[inset_0_1px_0_rgba(255,255,255,.03)]",female?"border-pink-400/22 bg-[radial-gradient(420px_180px_at_50%_0,rgba(244,114,182,.06),transparent_58%),linear-gradient(180deg,rgba(2,6,23,.46),rgba(2,6,23,.22))]":"border-sky-400/22 bg-[radial-gradient(420px_180px_at_50%_0,rgba(56,189,248,.06),transparent_58%),linear-gradient(180deg,rgba(2,6,23,.46),rgba(2,6,23,.22))]") }><div className="mb-3 flex items-center justify-between gap-3 border-b border-white/8 px-1 pb-3"><div className={cn("text-[.84rem] font-black uppercase tracking-[.22em]",female?"text-pink-300":"text-sky-300")}>{label}</div><div className={cn("inline-flex h-[34px] min-w-[34px] items-center justify-center rounded-full border px-3 text-[.86rem] font-black",female?"border-pink-300/35 text-pink-100":"border-sky-300/35 text-sky-100")}>{items.length}</div></div><div className="flex min-h-0 flex-1 flex-col gap-3 overflow-auto pr-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{loading||!items.length?<EmptyState loading={loading}/>:items.map(item=><PersonCard key={item.id} item={item} onPick={()=>onPick(item.id)}/>)}</div></section>}
export default function Pick_Button({title="Избери крупие",picker,setPicker,loading,pickTab,setPickTab,pickQ,setPickQ,addStaff}){
  const inputRef=useRef(null),list=Array.isArray(picker)?picker:[];
  const q=(pickQ||"").toLowerCase().trim();
  const {women,men,totalCount}=useMemo(()=>{const byQ=item=>!q||String(item?.nickname||"").toLowerCase().includes(q);const women=list.filter(item=>item.gender==="FEMALE"&&byQ(item)),men=list.filter(item=>item.gender==="MALE"&&byQ(item));return{women,men,totalCount:women.length+men.length}},[list,q]);
  const resultCount=pickTab==="women"?women.length:pickTab==="men"?men.length:totalCount;
  const resultLabel=`${resultCount} ${resultCount===1?"резултат":"резултата"}`;
  useEffect(()=>{if(!picker)return;const onKey=e=>e.key==="Escape"&&setPicker?.(null);window.addEventListener("keydown",onKey);const t=setTimeout(()=>inputRef.current?.focus(),80);return()=>{window.removeEventListener("keydown",onKey);clearTimeout(t)};},[picker,setPicker]);
  if(!picker)return null;
  return <AnimatePresence><motion.div className="fixed inset-0 z-[9999] grid place-items-center bg-[rgba(2,6,23,.78)] p-3 backdrop-blur-[8px]" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.18,ease:EASE}} onMouseDown={()=>setPicker?.(null)}><motion.div initial={{opacity:0,scale:.985,y:10}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:.985,y:10}} transition={{duration:.2,ease:EASE}} className="relative w-[min(760px,94vw)] h-[min(84vh,760px)] max-h-[84vh] overflow-hidden rounded-[30px] border border-cyan-400/55 bg-[radial-gradient(980px_500px_at_8%_0%,rgba(56,189,248,.18),transparent_58%),radial-gradient(760px_420px_at_100%_0%,rgba(16,185,129,.14),transparent_58%),linear-gradient(180deg,rgba(15,23,42,.98),rgba(2,6,23,1))] p-0 shadow-[0_24px_64px_rgba(0,0,0,.55)]" onMouseDown={e=>e.stopPropagation()}><div className="absolute inset-0 rounded-[30px] bg-[linear-gradient(180deg,rgba(255,255,255,.02),transparent_18%,transparent_82%,rgba(16,185,129,.03))]"/><div className="relative flex h-full min-h-0 flex-col gap-5 p-6 max-[640px]:gap-4 max-[640px]:p-4"><div className="relative border-b border-white/10 pb-4 pr-16 max-[640px]:pr-12"><div className="text-center"><div className="mb-1 text-[.72rem] uppercase tracking-[.36em] text-cyan-200/70">Крупие</div><h3 className="m-0 text-[1.08rem] font-black uppercase tracking-[.22em] text-[#eef6ff] max-[640px]:text-[.94rem] max-[640px]:tracking-[.18em]">{title}</h3><div className="mt-2 text-[.78rem] font-extrabold uppercase tracking-[.12em] text-white/60">{resultLabel}</div></div><div className="absolute right-0 top-0"><CloseButton onClick={()=>setPicker?.(null)}/></div></div><div className="grid grid-cols-[minmax(0,1fr)_290px] gap-4 items-center max-[640px]:grid-cols-1"><div className="flex flex-wrap items-center gap-3 rounded-full border border-white/10 bg-[linear-gradient(180deg,rgba(2,6,23,.40),rgba(2,6,23,.22))] p-1.5 shadow-[inset_0_1px_0_rgba(255,255,255,.04)] max-[640px]:justify-center">{TABS.map(tab=><TabButton key={tab.id} label={tab.label} tone={tab.tone} active={pickTab===tab.id} onClick={()=>setPickTab?.(tab.id)}/> )}</div><SearchField value={pickQ} onChange={setPickQ} inputRef={inputRef}/></div><div className={cn("grid flex-1 min-h-0 gap-4 overflow-auto pr-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden",pickTab==="all"?"grid-cols-2 max-[640px]:grid-cols-1":"grid-cols-1")}>{pickTab==="women"?<Column label="ЖЕНИ" tone="female" items={women} loading={loading} onPick={addStaff}/>:pickTab==="men"?<Column label="МЪЖЕ" tone="male" items={men} loading={loading} onPick={addStaff}/>:<><Column label="ЖЕНИ" tone="female" items={women} loading={loading} onPick={addStaff}/><Column label="МЪЖЕ" tone="male" items={men} loading={loading} onPick={addStaff}/></>}</div></div></motion.div></motion.div></AnimatePresence>;
}
