"use client";
import {useEffect,useMemo,useRef} from "react";
import {AnimatePresence,motion} from "framer-motion";
const EASE=[.4,0,.2,1],MONTHS=["Януари","Февруари","Март","Април","Май","Юни","Юли","Август","Септември","Октомври","Ноември","Декември"],cn=(...v)=>v.filter(Boolean).join(" ");
const XIcon=({className=""})=><svg viewBox="0 0 24 24" className={className} fill="none" aria-hidden="true"><path d="M7 7l10 10M17 7L7 17" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round"/></svg>;
const SearchIcon=({className=""})=><svg viewBox="0 0 24 24" className={className} fill="none" aria-hidden="true"><circle cx="11" cy="11" r="5.5" stroke="currentColor" strokeWidth="2"/><path d="M16 16l4 4" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></svg>;
function monthText(month,year){return month&&year?`${MONTHS[(month-1+12)%12]||""} ${year}`.trim():""}
function roleLabel(title){const raw=String(title||"").replace(/^Избери\s+/i,"").trim();if(!raw)return"крупиета";if(raw.toLowerCase()==="крупие")return"крупиета";return raw.toLowerCase()}
function CloseButton({onClick}){return <button type="button" onClick={onClick} aria-label="Close" className="group relative grid h-[52px] w-[52px] place-items-center rounded-[18px] bg-gradient-to-br from-emerald-500 via-teal-600 to-emerald-600 p-px shadow-[0_18px_42px_rgba(0,0,0,.44)]"><span className="pointer-events-none absolute inset-0 rounded-[18px] bg-gradient-to-br from-white/10 via-transparent to-transparent opacity-40"/><span className="relative grid h-full w-full place-items-center overflow-hidden rounded-[17px] bg-[linear-gradient(180deg,rgba(2,8,13,.985),rgba(2,6,11,.985))] text-white/90"><span className="absolute inset-0 rounded-[17px] bg-[radial-gradient(200px_88px_at_50%_-20%,rgba(0,255,210,.15),transparent_58%),radial-gradient(120px_60px_at_86%_16%,rgba(80,170,255,.08),transparent_60%)]"/><span className="absolute inset-0 rounded-[17px] shadow-[inset_0_1px_1px_rgba(16,185,129,.1)]"/><XIcon className="relative h-[18px] w-[18px] transition duration-200 group-hover:scale-110"/></span></button>}
function TabButton({active,label,count,tone,onClick}){const tones=tone==="female"?active?"border-fuchsia-400/90 text-white bg-[linear-gradient(180deg,rgba(57,15,40,.96),rgba(20,7,17,.98))] shadow-[0_0_0_1px_rgba(244,114,182,.16),0_14px_28px_rgba(0,0,0,.28)]":"border-fuchsia-400/35 text-fuchsia-100/88 hover:border-fuchsia-300/65":tone==="male"?active?"border-cyan-300/90 text-white bg-[linear-gradient(180deg,rgba(7,33,42,.96),rgba(4,11,16,.98))] shadow-[0_0_0_1px_rgba(34,211,238,.16),0_14px_28px_rgba(0,0,0,.28)]":"border-cyan-400/35 text-cyan-100/88 hover:border-cyan-300/65":active?"border-emerald-300/90 text-white bg-[linear-gradient(180deg,rgba(3,35,40,.96),rgba(3,12,18,.98))] shadow-[0_0_0_1px_rgba(0,255,210,.12),0_14px_28px_rgba(0,0,0,.28)]":"border-emerald-400/35 text-white/84 hover:border-emerald-300/65";return <button type="button" onClick={onClick} className={cn("group relative overflow-hidden rounded-[18px] border bg-[linear-gradient(180deg,rgba(6,12,20,.96),rgba(3,8,13,.98))] px-4 py-3 text-center transition duration-200 hover:-translate-y-[1px]",tones)}><span className="absolute inset-0 bg-[radial-gradient(180px_80px_at_22%_10%,rgba(255,255,255,.05),transparent_62%)] opacity-70"/><span className="relative block text-[.82rem] font-black uppercase tracking-[.18em]">{label}</span><span className="relative mt-1 block text-[.96rem] font-black text-white/95">({count})</span><motion.span initial={false} animate={active?{scaleX:1,opacity:1}:{scaleX:0,opacity:0}} transition={{duration:.2,ease:EASE}} className="absolute bottom-[9px] left-4 right-4 h-px origin-left bg-gradient-to-r from-emerald-300 via-teal-300 to-transparent"/></button>}
function SearchField({value,onChange,inputRef}){return <label className="group relative flex h-[68px] items-center overflow-hidden rounded-[20px] border border-emerald-400/45 bg-[linear-gradient(180deg,rgba(5,14,20,.98),rgba(2,7,11,.99))] px-4 transition duration-200 hover:border-emerald-300/65 focus-within:border-emerald-300/95 focus-within:shadow-[0_0_0_1px_rgba(16,185,129,.16)]"><span className="absolute inset-0 bg-[radial-gradient(220px_100px_at_18%_0,rgba(0,255,210,.08),transparent_55%),radial-gradient(140px_70px_at_86%_16%,rgba(80,170,255,.06),transparent_58%)]"/><SearchIcon className="relative mr-3 h-[18px] w-[18px] text-emerald-200/80"/><input ref={inputRef} value={value} onChange={e=>onChange(e.target.value)} placeholder="Search..." autoComplete="off" className="relative h-full w-full bg-transparent text-[1.02rem] font-bold text-white outline-none placeholder:text-white/40"/></label>}
function PersonCard({item,onPick,tone}){const styles=tone==="female"?"border-fuchsia-400/28 text-fuchsia-50 hover:border-fuchsia-300/58 hover:shadow-[0_0_0_1px_rgba(236,72,153,.1),0_14px_28px_rgba(0,0,0,.24)]":"border-cyan-400/28 text-cyan-50 hover:border-cyan-300/58 hover:shadow-[0_0_0_1px_rgba(34,211,238,.1),0_14px_28px_rgba(0,0,0,.24)]";return <motion.button whileTap={{scale:.988}} type="button" onClick={onPick} className={cn("group relative flex min-h-[58px] items-center overflow-hidden rounded-[18px] border bg-[linear-gradient(180deg,rgba(4,10,16,.98),rgba(2,7,11,.99))] px-5 text-left transition duration-150 hover:-translate-y-[1px]",styles)}><span className="absolute inset-0 bg-[radial-gradient(180px_70px_at_18%_10%,rgba(255,255,255,.04),transparent_62%)] opacity-80"/><span className="relative truncate text-[1rem] font-black uppercase tracking-[.04em] text-white/92">{item.nickname||"—"}</span></motion.button>}
function EmptyState({loading}){return <div className="flex min-h-[180px] items-center justify-center rounded-[22px] border border-dashed border-white/10 bg-black/20 px-4 text-center text-[.95rem] font-bold text-white/45">{loading?"Зареждане...":"Няма намерени крупиета"}</div>}
function Column({label,tone,items,loading,onPick}){const headTone=tone==="female"?"text-fuchsia-300 border-fuchsia-400/22 bg-[radial-gradient(360px_140px_at_50%_0,rgba(236,72,153,.08),transparent_58%),linear-gradient(180deg,rgba(4,10,16,.66),rgba(2,7,11,.38))]":"text-cyan-300 border-cyan-400/22 bg-[radial-gradient(360px_140px_at_50%_0,rgba(34,211,238,.08),transparent_58%),linear-gradient(180deg,rgba(4,10,16,.66),rgba(2,7,11,.38))]";return <section className={cn("relative flex min-h-0 flex-col overflow-hidden rounded-[24px] border p-4 shadow-[inset_0_1px_0_rgba(255,255,255,.03)]",headTone)}><div className="mb-3 border-b border-white/8 pb-3"><div className={cn("text-[.88rem] font-black uppercase tracking-[.22em]",tone==="female"?"text-fuchsia-300":"text-cyan-300")}>{label}</div></div><div className="flex min-h-0 flex-1 flex-col gap-3 overflow-auto pr-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{loading||!items.length?<EmptyState loading={loading}/>:items.map(item=><PersonCard key={item.id} item={item} tone={tone} onPick={()=>onPick(item.id)}/>)}</div></section>}
export default function Pick_Button({title="Избери крупие",picker,setPicker,loading,pickTab,setPickTab,pickQ,setPickQ,addStaff,month,year}){
  const inputRef=useRef(null),list=Array.isArray(picker)?picker:[];
  const q=(pickQ||"").toLowerCase().trim();
  const {women,men}=useMemo(()=>{const byQ=item=>!q||String(item?.nickname||"").toLowerCase().includes(q);return{women:list.filter(item=>item.gender==="FEMALE"&&byQ(item)),men:list.filter(item=>item.gender==="MALE"&&byQ(item))};},[list,q]);
  useEffect(()=>{if(!picker)return;const onKey=e=>e.key==="Escape"&&setPicker?.(null);window.addEventListener("keydown",onKey);const t=setTimeout(()=>inputRef.current?.focus(),80);return()=>{window.removeEventListener("keydown",onKey);clearTimeout(t)};},[picker,setPicker]);
  if(!picker)return null;
  const total=women.length+men.length,monthLabel=monthText(month,year),heading=`Избор на ${roleLabel(title)}${monthLabel?` за ${monthLabel}`:" за месеца"}`;
  const tabs=[{id:"all",label:"ВСИЧКИ",count:total,tone:"all"},{id:"women",label:"ЖЕНИ",count:women.length,tone:"female"},{id:"men",label:"МЪЖЕ",count:men.length,tone:"male"}];
  return <AnimatePresence><motion.div className="fixed inset-0 z-[9999] grid place-items-center bg-[rgba(0,0,0,.84)] p-4 backdrop-blur-[6px]" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.18,ease:EASE}} onMouseDown={()=>setPicker?.(null)}><motion.div initial={{opacity:0,scale:.986,y:10}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:.986,y:10}} transition={{duration:.2,ease:EASE}} onMouseDown={e=>e.stopPropagation()} className="relative w-[min(680px,92vw)] h-[min(76vh,760px)] max-h-[76vh] overflow-hidden rounded-[28px] border border-emerald-400/60 bg-[radial-gradient(920px_340px_at_18%_0,rgba(16,185,129,.16),transparent_56%),radial-gradient(720px_260px_at_100%_0,rgba(34,211,238,.08),transparent_58%),linear-gradient(180deg,rgba(4,12,16,.985),rgba(2,7,11,.995))] shadow-[0_26px_70px_rgba(0,0,0,.62)]"><span className="absolute inset-0 rounded-[28px] bg-[linear-gradient(180deg,rgba(255,255,255,.02),transparent_18%,transparent_82%,rgba(16,185,129,.03))]"/><div className="relative flex h-full min-h-0 flex-col gap-4 p-5"><div className="relative border-b border-white/10 pb-4 pr-16"><div className="text-center"><h3 className="m-0 text-[1.02rem] font-black uppercase tracking-[.18em] text-white/94">{heading}</h3></div><div className="absolute right-0 top-0"><CloseButton onClick={()=>setPicker?.(null)}/></div></div><div className="grid grid-cols-[minmax(0,1fr)_240px] items-stretch gap-3 max-[760px]:grid-cols-1"><div className="grid min-w-0 grid-cols-3 gap-2">{tabs.map(tab=><TabButton key={tab.id} label={tab.label} count={tab.count} tone={tab.tone} active={pickTab===tab.id} onClick={()=>setPickTab?.(tab.id)}/>)}</div><SearchField value={pickQ} onChange={setPickQ} inputRef={inputRef}/></div><div className={cn("grid flex-1 min-h-0 gap-4 overflow-auto pr-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden",pickTab==="all"?"grid-cols-2 max-[760px]:grid-cols-1":"grid-cols-1")}>{pickTab==="women"?<Column label="ЖЕНИ" tone="female" items={women} loading={loading} onPick={addStaff}/>:pickTab==="men"?<Column label="МЪЖЕ" tone="male" items={men} loading={loading} onPick={addStaff}/>:<><Column label="ЖЕНИ" tone="female" items={women} loading={loading} onPick={addStaff}/><Column label="МЪЖЕ" tone="male" items={men} loading={loading} onPick={addStaff}/></>}</div></div></motion.div></motion.div></AnimatePresence>;
}
