"use client";
import {memo,useEffect,useLayoutEffect,useMemo,useRef,useState} from "react";
const cn=(...v)=>v.filter(Boolean).join(" "),NAME_W=106,DAY_W=56,DAY_CARD_W=106,ROW_H=36,HEAD_H=36,STAT_W=[72,50,45,68,62,58,45],GRID_GAP=3,PAD=4,TOP_X_PAD=5,TOP_Y_PAD=4,TOP_GAP=6,TOP_VISIBLE_DAYS=16,TOP_CARD_H=142,VISIBLE_ROWS=19,BODY_H=VISIBLE_ROWS*ROW_H+(VISIBLE_ROWS-1)*GRID_GAP+PAD*2-1,CELL_SEL='[data-slot-input]',ROW_SEL='[data-row]',EMPTY_STATS=Object.freeze({}),nameTone=g=>g==="FEMALE"?"border-fuchsia-500/40 bg-[#16081e] text-fuchsia-50":"border-sky-500/40 bg-[#071525] text-sky-50",DAY_BG="#05101a",DAY_BORDER="rgba(34,211,238,.25)",DAY_BG_ACTIVE="#0a1826",DAY_BORDER_ACTIVE="rgba(103,232,249,.98)",ROW_BG_ACTIVE="#081520",ROW_BORDER_ACTIVE="rgba(103,232,249,.98)",BOTH_BG_ACTIVE="#0c2030",BOTH_BORDER_ACTIVE="rgba(103,232,249,.98)",STAT_BG="#08111a",STAT_BORDER="rgba(103,232,249,.24)",STAT_BG_ACTIVE="#0a1826",STAT_BORDER_ACTIVE="rgba(103,232,249,.98)",HEAD_BG_ACTIVE="#08131d",HEAD_BORDER_ACTIVE="rgba(103,232,249,.98)",TOP_WEEKDAY_BORDER="rgba(34,211,238,.40)",TOP_WEEKDAY_BORDER_ACTIVE="rgba(103,232,249,.98)",TOP_WEEKEND_BORDER="rgba(214,184,102,.82)",TOP_WEEKEND_BORDER_ACTIVE="rgba(240,214,120,.98)",TOP_CARD_BG="#05101a",TOP_CARD_BG_ACTIVE="#0a1826";
const rid=row=>row?.staffId??row?.id??row?.staff?.id??null;
const setRef=(ref,node)=>{if(!ref)return;if(typeof ref==="function")ref(node);else ref.current=node};
const focusEnd=i=>{if(!i)return;const l=(i.value||"").length;i.focus();try{i.setSelectionRange(l,l)}catch{}};
const cols=(days,stats)=>(days||[]).map(()=>`${DAY_W}px`).concat((stats||[]).map((_,i)=>`${STAT_W[i]||Math.round(DAY_W*1.1)}px`)).join(" ");
const panel="box-border bg-[#020813] border border-cyan-400/25",cell="box-border border border-cyan-400/25 bg-[#05101a]",statCell="box-border border border-cyan-400/24 bg-[#08111a]",offCell="box-border border border-white/10 bg-white/[0.025]",sel="bg-[#08131d]";
const sameRows=(a,b,checkName)=>{if(a===b)return true;const al=a||[],bl=b||[];if(al.length!==bl.length)return false;for(let i=0;i<al.length;i++){const ar=al[i],br=bl[i];if(rid(ar)!==rid(br))return false;if(checkName&&(ar?.staff?.nickname!==br?.staff?.nickname||ar?.staff?.gender!==br?.staff?.gender))return false;}return true};
const fmtWeekday=v=>{if(!v)return"";const s=String(v).trim().toLowerCase();return s?s.charAt(0).toUpperCase()+s.slice(1):""};
const isWeekend=v=>{const s=String(v||"").trim().toLowerCase();return s==="събота"||s==="неделя"||s==="saturday"||s==="sunday"};
const useTopCardWidth=(ref,visible,sidePad,gap,fallback)=>{const [w,setW]=useState(fallback);useLayoutEffect(()=>{const el=ref.current;if(!el)return;let raf=0;const calc=()=>{const raw=(el.clientWidth-sidePad*2-gap*(visible-1))/visible,next=Math.max(fallback,Number(raw.toFixed(3)));setW(p=>p===next?p:next)};const run=()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(calc)};run();const ro=new ResizeObserver(run);ro.observe(el);return()=>{cancelAnimationFrame(raf);ro.disconnect()}},[ref,visible,sidePad,gap,fallback]);return w};
const paintCell=el=>{if(!el)return;const off=el.dataset.off==="1",dayActive=el.dataset.dayActive==="1",rowActive=el.dataset.rowActive==="1";if(off){el.style.background="rgba(255,255,255,.025)";el.style.borderColor="rgba(255,255,255,.10)";return;}el.style.background=dayActive&&rowActive?BOTH_BG_ACTIVE:dayActive?DAY_BG_ACTIVE:rowActive?ROW_BG_ACTIVE:DAY_BG;el.style.borderColor=dayActive&&rowActive?BOTH_BORDER_ACTIVE:dayActive?DAY_BORDER_ACTIVE:rowActive?ROW_BORDER_ACTIVE:DAY_BORDER};
const paintHeadDay=el=>{if(!el)return;const off=el.dataset.off==="1",dayActive=el.dataset.dayActive==="1";if(off){el.style.background="rgba(255,255,255,.025)";el.style.borderColor="rgba(255,255,255,.10)";el.style.color="rgba(255,255,255,.4)";return;}el.style.background=dayActive?HEAD_BG_ACTIVE:DAY_BG;el.style.borderColor=dayActive?HEAD_BORDER_ACTIVE:DAY_BORDER;el.style.color=dayActive?"rgba(255,255,255,.96)":"rgba(255,255,255,.82)"};
const paintStat=el=>{if(!el)return;const rowActive=el.dataset.rowActive==="1";el.style.background=rowActive?STAT_BG_ACTIVE:STAT_BG;el.style.borderColor=rowActive?STAT_BORDER_ACTIVE:STAT_BORDER};
const paintNameCard=el=>{if(!el)return;const female=el.dataset.gender==="FEMALE",rowActive=el.dataset.rowActive==="1";el.style.background=rowActive?(female?"#261133":"#0d2237"):(female?"#16081e":"#071525");el.style.borderColor=rowActive?(female?"rgba(217,70,239,.9)":"rgba(56,189,248,.9)"):(female?"rgba(217,70,239,.4)":"rgba(14,165,233,.4)");el.style.boxShadow="none"};
const DayStrip=memo(function DayStrip({days,daysInMonth,weekdayByDay,dcByDay,dcSorted,activeDay,onPickDay,topRef,viewportRef,cardW}){
  return <div ref={node=>{setRef(topRef,node);setRef(viewportRef,node)}} className={`${panel} shrink-0 overflow-x-auto rounded-[9px] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden`} style={{padding:`${TOP_Y_PAD}px ${TOP_X_PAD}px`}}><div className="flex w-max" style={{gap:TOP_GAP}}>{(days||[]).map(d=>{const off=d>daysInMonth,st=dcByDay?.[d-1]||{},isSel=activeDay===d,weekday=fmtWeekday(weekdayByDay?.[d-1]||""),weekend=isWeekend(weekday),borderColor=off?"rgba(255,255,255,.10)":weekend?(isSel?TOP_WEEKEND_BORDER_ACTIVE:TOP_WEEKEND_BORDER):isSel?TOP_WEEKDAY_BORDER_ACTIVE:TOP_WEEKDAY_BORDER,bgColor=off?"rgba(255,255,255,.025)":isSel?TOP_CARD_BG_ACTIVE:TOP_CARD_BG;return <button key={d} type="button" onClick={()=>onPickDay?.(d)} className={cn("box-border rounded-[7px] px-2 text-center",off?offCell:cn(cell,isSel?sel:""))} style={{width:cardW,minWidth:cardW,maxWidth:cardW,height:TOP_CARD_H,minHeight:TOP_CARD_H,borderWidth:3,borderColor,background:bgColor,boxShadow:"none"}}><div className="flex h-full flex-col items-center"><div className="flex flex-col items-center" style={{paddingTop:5}}><div className={cn("text-[15px] font-black leading-none",off?"text-white/40":"text-white")}>{`Ден ${d}`}</div><div className={cn("mt-1 text-[14px] font-black leading-none tracking-[.04em]",off?"text-white/42":weekend?"text-[#e0c874]":"text-white")}>{weekday}</div></div><div className="mt-2 flex flex-1 flex-col justify-center gap-0.5" style={{transform:"translateY(-5px)"}}>{dcSorted?.length?dcSorted.map(sec=><div key={sec.id} className="mx-auto grid w-fit grid-cols-[46px_22px] items-center gap-x-3 leading-none"><span className={cn("text-left text-[15px] font-bold whitespace-nowrap",off?"text-white/40":isSel?"text-white":"text-white/82")}>{sec.name}</span><span className={cn("flex h-[18px] min-w-[22px] items-center justify-center rounded-[5px] px-1 text-[14px] font-black",off?"bg-white/6 text-white/36":isSel?"bg-emerald-400/18 text-emerald-100":"bg-emerald-500/14 text-emerald-200")}>{st?.[sec.id]||0}</span></div>):<div className={cn("text-center text-[12px] font-bold",off?"text-white/30":isSel?"text-white/58":"text-white/42")}>—</div>}</div></div></button>})}</div></div>;
});
const HeaderGrid=memo(function HeaderGrid({days,daysInMonth,activeDay,onPickDay,headScrollRef,statsLabels,gridTemplate}){
  return <div className="relative flex items-stretch border-b border-white/8" style={{padding:`${PAD}px ${PAD}px 0`}}><div className="shrink-0" style={{width:NAME_W,paddingRight:GRID_GAP}}><div className={`${panel} flex items-center justify-center rounded-[5px] text-center text-[16px] font-black tracking-[.06em] text-white`} style={{height:HEAD_H}}>Имена</div></div><div ref={headScrollRef} className="min-w-0 flex-1 overflow-x-auto overflow-y-hidden [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><div className="grid w-max" style={{gridTemplateColumns:gridTemplate,columnGap:GRID_GAP,rowGap:0,paddingBottom:GRID_GAP}}>{(days||[]).map(d=>{const off=d>daysInMonth,isSel=activeDay===d;return <button key={d} type="button" data-head-day data-day={d} data-off={off?1:0} data-day-active={isSel?1:0} onClick={()=>onPickDay?.(d)} className={cn("box-border flex items-center justify-center rounded-[5px] text-[14px] font-black",off?offCell:`${cell} text-white/82 ${isSel?sel:""}`)} style={{height:HEAD_H,width:DAY_W}}>{d}</button>})}{(statsLabels||[]).map((s,i)=><div key={`hs-${i}`} className={`${statCell} box-border flex items-center justify-center rounded-[5px] px-1 text-center text-[13px] font-black uppercase tracking-[.08em] text-cyan-50/92`} style={{height:HEAD_H,width:STAT_W[i]||Math.round(DAY_W*1.1)}}>{s}</div>)}</div></div></div>;
});
const NameColumn=memo(function NameColumn({sortedRows,namesRef,setActiveStaffId}){
  return <div ref={namesRef} className="sticky left-0 z-20 shrink-0 bg-[#020813]" style={{width:NAME_W,paddingRight:GRID_GAP}}><div className="flex flex-col" style={{gap:GRID_GAP}}>{(sortedRows||[]).map((row,i)=>{const rowId=rid(row)??`n-${i}`;return <button key={rowId} type="button" data-name-card data-staff-key={String(rowId)} data-gender={row?.staff?.gender||""} onClick={()=>setActiveStaffId?.(rowId)} className={cn("box-border flex items-center rounded-[5px] border px-3 text-left",nameTone(row?.staff?.gender))} style={{height:ROW_H}}><span data-name-txt className="block w-full truncate text-[15px] font-black leading-none tracking-[.02em]">{row?.staff?.nickname||""}</span></button>})}</div></div>;
},(a,b)=>sameRows(a.sortedRows,b.sortedRows,true));
const ScheduleRow=memo(function ScheduleRow({row,index,days,daysInMonth,setActiveDay,setActiveStaffId,setSchedule,tableRef,saveCell,stats,statsLabels,gridTemplate}){
  const rowId=String(rid(row)??`r-${index}`);
  return <div data-row data-staff-key={rowId} className="grid w-max" style={{gridTemplateColumns:gridTemplate,columnGap:GRID_GAP,rowGap:0,contain:"layout paint style"}} onMouseDownCapture={()=>setActiveStaffId?.(rowId)}>{(days||[]).map(d=>{const off=d>daysInMonth,field=`day${d}`,val=row?.[field]||"";if(off)return <div key={d} data-slot-cell data-day={d} data-staff-key={rowId} data-off="1" className={`${offCell} box-border flex items-center justify-center rounded-[5px] text-[12px] font-black text-white/28`} style={{height:ROW_H,width:DAY_W}}>X</div>;return <div key={d} data-slot-cell data-day={d} data-staff-key={rowId} data-off="0" className={`${cell} box-border flex items-center justify-center rounded-[5px]`} style={{height:ROW_H,width:DAY_W}} onMouseDown={e=>{const inp=e.currentTarget.querySelector(CELL_SEL);if(!inp||document.activeElement===inp)return;e.preventDefault();focusEnd(inp);setActiveDay?.(d);setActiveStaffId?.(rowId);}}><input data-slot-input className="h-full w-full bg-transparent px-1 text-center text-[13px] font-bold text-white outline-none placeholder:text-white/22" autoComplete="off" spellCheck={false} value={val} onChange={e=>{const v=e.target.value;setSchedule?.(s=>!s?s:{...s,rows:(s.rows||[]).map(r=>((r.staffId??r.id??r.staff?.id)===(row.staffId??row.id??row.staff?.id))?{...r,[field]:v}:r)})}} onBlur={e=>saveCell?.((row.staffId??row.id??row.staff?.id),d,e.target.value)} onMouseDown={e=>{if(document.activeElement===e.currentTarget)e.stopPropagation()}} onFocus={e=>{focusEnd(e.target);setActiveDay?.(d);setActiveStaffId?.(rowId)}} onKeyDown={e=>{const input=e.currentTarget,v=input.value||"",pos=input.selectionStart??v.length,rowEl=input.closest(ROW_SEL),table=tableRef?.current||rowEl?.parentElement;if(e.key==="ArrowLeft"&&pos===0&&d>1){e.preventDefault();const prev=rowEl?.querySelector(`[data-slot-cell][data-day="${d-1}"] ${CELL_SEL}`);if(prev){focusEnd(prev);setActiveDay?.(d-1);setActiveStaffId?.(rowId)}}else if(e.key==="ArrowRight"&&pos===v.length&&d<daysInMonth){e.preventDefault();const next=rowEl?.querySelector(`[data-slot-cell][data-day="${d+1}"] ${CELL_SEL}`);if(next){focusEnd(next);setActiveDay?.(d+1);setActiveStaffId?.(rowId)}}else if((e.key==="ArrowUp"||e.key==="ArrowDown"||e.key==="Enter")&&table&&rowEl){e.preventDefault();const rows=[...table.querySelectorAll(ROW_SEL)],ri=rows.indexOf(rowEl),ti=e.key==="ArrowUp"?ri-1:ri+1;if(ti<0||ti>=rows.length)return;const next=rows[ti]?.querySelector(`[data-slot-cell][data-day="${d}"] ${CELL_SEL}`);if(next){focusEnd(next);setActiveDay?.(d);setActiveStaffId?.(rows[ti]?.dataset?.staffKey||null)}}}}/></div>})}{(statsLabels||[]).map((s,si)=><div key={`${rowId}-st-${si}`} data-stat-cell data-staff-key={rowId} className={`${statCell} box-border flex items-center justify-center rounded-[5px] px-1 text-[15px] font-black text-cyan-50/92`} style={{height:ROW_H,width:STAT_W[si]||Math.round(DAY_W*1.1)}}>{stats?.[s]??"0"}</div>)}</div>;
},(a,b)=>a.row===b.row&&a.stats===b.stats&&a.days===b.days&&a.daysInMonth===b.daysInMonth&&a.gridTemplate===b.gridTemplate&&a.statsLabels===b.statsLabels);
export default function Schedule({days,daysInMonth,weekdayByDay,dcByDay,dcSorted,activeDay,setActiveDay,topRef,gridScrollRef,headScrollRef,namesRef,sortedRows,setSchedule,tableRef,saveCell,statsByStaffId,hScrollRef,hScrollW,statsLabels}){
  const rootRef=useRef(null),safeDays=useMemo(()=>days?.length?days:Array.from({length:31},(_,i)=>i+1),[days]),gridTemplate=useMemo(()=>cols(safeDays,statsLabels||[]),[safeDays,statsLabels]),topViewportRef=useRef(null),bodyRef=useRef(null),topCardW=useTopCardWidth(topViewportRef,TOP_VISIBLE_DAYS,TOP_X_PAD,TOP_GAP,DAY_CARD_W),[activeStaffId,setActiveStaffId]=useState(null),pickDay=d=>{setActiveDay?.(d);if(String(d)!==String(activeDay))setActiveStaffId(null)},clearPick=()=>{setActiveDay?.(null);setActiveStaffId(null)};
  useLayoutEffect(()=>{if(activeStaffId==null)return;const hasRow=(sortedRows||[]).some(r=>String(rid(r))===String(activeStaffId));if(!hasRow)setActiveStaffId(null)},[activeStaffId,sortedRows]);
  useEffect(()=>{const onDown=e=>{const root=rootRef.current;if(root&&root.contains(e.target))return;clearPick()};document.addEventListener("pointerdown",onDown,true);return()=>document.removeEventListener("pointerdown",onDown,true)},[clearPick]);
  useLayoutEffect(()=>{const root=bodyRef.current;if(!root)return;root.querySelectorAll("[data-slot-cell]").forEach(el=>{el.dataset.dayActive=activeDay!=null&&String(el.dataset.day)===String(activeDay)?"1":"0";paintCell(el)});root.querySelectorAll("[data-head-day]").forEach(el=>{el.dataset.dayActive=activeDay!=null&&String(el.dataset.day)===String(activeDay)?"1":"0";paintHeadDay(el)});root.querySelectorAll("[data-name-card]").forEach(el=>{el.dataset.rowActive=activeStaffId!=null&&String(el.dataset.staffKey)===String(activeStaffId)?"1":"0";paintNameCard(el)});root.querySelectorAll("[data-stat-cell]").forEach(el=>{el.dataset.rowActive=activeStaffId!=null&&String(el.dataset.staffKey)===String(activeStaffId)?"1":"0";paintStat(el)});root.querySelectorAll("[data-slot-cell][data-staff-key]").forEach(el=>{el.dataset.rowActive=activeStaffId!=null&&String(el.dataset.staffKey)===String(activeStaffId)?"1":"0";paintCell(el)})},[activeDay,activeStaffId,safeDays,sortedRows,statsLabels]);
  return <div ref={rootRef} className="flex w-full flex-col overflow-hidden" style={{gap:5}}><DayStrip days={safeDays} daysInMonth={daysInMonth} weekdayByDay={weekdayByDay} dcByDay={dcByDay} dcSorted={dcSorted} activeDay={activeDay} onPickDay={pickDay} topRef={topRef} viewportRef={topViewportRef} cardW={topCardW}/><div ref={bodyRef} className="flex flex-none flex-col overflow-hidden rounded-[9px] border border-cyan-400/35 bg-[#020813]"><HeaderGrid days={safeDays} daysInMonth={daysInMonth} activeDay={activeDay} onPickDay={pickDay} headScrollRef={headScrollRef} statsLabels={statsLabels} gridTemplate={gridTemplate}/><div ref={gridScrollRef} className="overflow-auto [scrollbar-width:none] [&::-webkit-scrollbar]:hidden" style={{height:BODY_H,maxHeight:BODY_H,padding:PAD,contain:"layout paint"}}><div className="flex w-max items-start"><NameColumn sortedRows={sortedRows} namesRef={namesRef} setActiveStaffId={setActiveStaffId}/><div ref={tableRef} className="flex flex-col" style={{gap:GRID_GAP}}>{(sortedRows||[]).map((row,i)=><ScheduleRow key={rid(row)??`r-${i}`} row={row} index={i} days={safeDays} daysInMonth={daysInMonth} setActiveDay={setActiveDay} setActiveStaffId={setActiveStaffId} setSchedule={setSchedule} tableRef={tableRef} saveCell={saveCell} stats={statsByStaffId?.[String(rid(row)??`r-${i}`)]||EMPTY_STATS} statsLabels={statsLabels} gridTemplate={gridTemplate}/>)}</div></div></div></div><div className="shrink-0 overflow-visible rounded-[8px] border border-cyan-400/25 bg-[#020813] px-2 pt-0 pb-[1px]"><div ref={hScrollRef} className="block box-border h-[18px] min-h-[18px] overflow-x-auto overflow-y-hidden rounded-full border border-white/8 bg-[#07111d] [scrollbar-color:rgba(56,189,248,.85)_rgba(2,6,23,.45)] [scrollbar-width:thin] [&::-webkit-scrollbar]:h-[12px] [&::-webkit-scrollbar-thumb]:rounded-full [&::-webkit-scrollbar-thumb]:border [&::-webkit-scrollbar-thumb]:border-cyan-400/45 [&::-webkit-scrollbar-thumb]:bg-sky-400/85 [&::-webkit-scrollbar-track]:rounded-full [&::-webkit-scrollbar-track]:border [&::-webkit-scrollbar-track]:border-white/10 [&::-webkit-scrollbar-track]:bg-[#07111d]"><div style={{width:`${hScrollW||1}px`,height:1}}/></div></div></div>;
}
