"use client";
import {memo,useMemo} from "react";
const cn=(...v)=>v.filter(Boolean).join(" "),NAME_W=80,DAY_W=56,ROW_H=36,HEAD_H=36,STAT_W=[53,46,41,64,58,53,41],GRID_GAP=3,PAD=6,VISIBLE_ROWS=18,BODY_H=VISIBLE_ROWS*ROW_H+(VISIBLE_ROWS-1)*GRID_GAP+PAD*2-1,CELL_SEL='[data-slot-cell]',INPUT_SEL='[data-slot-input]',ROW_SEL='[data-row]',EMPTY_STATS=Object.freeze({}),nameTone=g=>g==="FEMALE"?"border-fuchsia-500/40 bg-[#16081e] text-fuchsia-50":"border-sky-500/40 bg-[#071525] text-sky-50";
const rid=row=>row?.staffId??row?.id??row?.staff?.id??null;
const focusEnd=i=>{if(!i)return;const l=(i.value||"").length;i.focus();try{i.setSelectionRange(l,l)}catch{}};
const cols=(days,stats)=>(days||[]).map(()=>`${DAY_W}px`).concat((stats||[]).map((_,i)=>`${STAT_W[i]||Math.round(DAY_W*1.1)}px`)).join(" ");
const panel="box-border bg-[#020813] border border-cyan-400/25",cell="box-border border border-cyan-400/25 bg-[#05101a]",statCell="box-border border border-violet-400/26 bg-[#10081a]",offCell="box-border border border-white/10 bg-white/[0.025]",sel="border-emerald-400/70 bg-emerald-500/[0.08]";
const sameRows=(a,b,checkName)=>{if(a===b)return true;const al=a||[],bl=b||[];if(al.length!==bl.length)return false;for(let i=0;i<al.length;i++){const ar=al[i],br=bl[i];if(rid(ar)!==rid(br))return false;if(checkName&&(ar?.staff?.nickname!==br?.staff?.nickname||ar?.staff?.gender!==br?.staff?.gender))return false;}return true};
const DayStrip=memo(function DayStrip({days,daysInMonth,weekdayByDay,dcByDay,dcSorted,activeDay,setActiveDay,topRef}){
  return <div ref={topRef} className={`${panel} shrink-0 overflow-x-auto rounded-[9px] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden`} style={{padding:PAD}}><div className="flex w-max" style={{gap:GRID_GAP}}>{(days||[]).map(d=>{const off=d>daysInMonth,st=dcByDay?.[d-1]||{},isSel=activeDay===d;return <button key={d} type="button" onClick={()=>setActiveDay?.(d)} className={cn("box-border min-w-[100px] rounded-[7px] border px-3 py-2 text-left",off?offCell:`${cell} ${isSel?sel:""}`)}><div className="flex items-start justify-between gap-2"><div><div className={cn("text-[10px] font-black uppercase tracking-[.16em]",off?"text-white/35":"text-cyan-100/65")}>Ден</div><div className={cn("mt-0.5 text-[24px] font-black leading-none",off?"text-white/40":"text-white")}>{d}</div></div><div className={cn("rounded-[5px] border px-1.5 py-0.5 text-[9px] font-black uppercase tracking-[.14em]",off?"border-white/8 text-white/32":"border-white/10 text-white/62")}>{weekdayByDay?.[d-1]||""}</div></div><div className="mt-2 space-y-1">{dcSorted?.length?dcSorted.map(sec=><div key={sec.id} className="flex items-center justify-between gap-2 text-[10px] font-bold"><span className={cn("truncate",off?"text-white/34":"text-white/60")}>{sec.name}</span><span className={cn("rounded-[5px] px-1.5 py-[1px] text-[9px] font-black",off?"bg-white/6 text-white/36":"bg-emerald-500/14 text-emerald-200")}>{st?.[sec.id]||0}</span></div>):<div className={cn("text-center text-[11px] font-bold",off?"text-white/30":"text-white/42")}>—</div>}</div></button>})}</div></div>;
});
const HeaderGrid=memo(function HeaderGrid({days,daysInMonth,activeDay,setActiveDay,headScrollRef,statsLabels,gridTemplate}){
  return <div className="relative flex items-stretch border-b border-white/8" style={{padding:`${PAD}px ${PAD}px 0`}}><div className="shrink-0" style={{width:NAME_W,paddingRight:GRID_GAP}}><div className={`${panel} flex items-center justify-center rounded-[5px] text-center text-[13px] font-black uppercase tracking-[.16em] text-white`} style={{height:HEAD_H}}>Имена</div></div><div ref={headScrollRef} className="min-w-0 flex-1 overflow-x-auto overflow-y-hidden [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><div className="grid w-max" style={{gridTemplateColumns:gridTemplate,columnGap:GRID_GAP,rowGap:0,paddingBottom:GRID_GAP}}>{(days||[]).map(d=>{const off=d>daysInMonth,isSel=activeDay===d;return <button key={d} type="button" onClick={()=>setActiveDay?.(d)} className={cn("box-border flex items-center justify-center rounded-[5px] text-[14px] font-black",off?offCell:`${cell} text-white/82 ${isSel?sel:""}`)} style={{height:HEAD_H,width:DAY_W}}>{d}</button>})}{(statsLabels||[]).map((s,i)=><div key={`hs-${i}`} className={`${statCell} box-border flex items-center justify-center rounded-[5px] px-1 text-center text-[10px] font-black uppercase tracking-[.12em] text-violet-100/88`} style={{height:HEAD_H,width:STAT_W[i]||Math.round(DAY_W*1.1)}}>{s}</div>)}</div></div></div>;
});
const NameColumn=memo(function NameColumn({sortedRows,namesRef}){
  return <div ref={namesRef} className="sticky left-0 z-20 shrink-0 bg-[#020813]" style={{width:NAME_W,paddingRight:GRID_GAP}}><div className="flex flex-col" style={{gap:GRID_GAP}}>{(sortedRows||[]).map((row,i)=><div key={rid(row)??`n-${i}`} data-name-card className={cn("box-border flex items-center rounded-[5px] border px-3",nameTone(row?.staff?.gender))} style={{height:ROW_H}}><span data-name-txt className="block w-full truncate text-[15px] font-black leading-none tracking-[.02em]">{row?.staff?.nickname||""}</span></div>)}</div></div>;
},(a,b)=>sameRows(a.sortedRows,b.sortedRows,true));
const ScheduleRow=memo(function ScheduleRow({row,index,days,daysInMonth,setActiveDay,setSchedule,tableRef,saveCell,stats,statsLabels,gridTemplate}){
  const rowId=rid(row)??`r-${index}`;
  return <div data-row className="grid w-max" style={{gridTemplateColumns:gridTemplate,columnGap:GRID_GAP,rowGap:0,contain:"layout paint style"}}>{(days||[]).map(d=>{const off=d>daysInMonth,field=`day${d}`,val=row?.[field]||"";if(off)return <div key={d} className={`${offCell} box-border flex items-center justify-center rounded-[5px] text-[12px] font-black text-white/28`} style={{height:ROW_H,width:DAY_W}}>X</div>;return <div key={d} data-slot-cell className={`${cell} box-border flex items-center justify-center rounded-[5px]`} style={{height:ROW_H,width:DAY_W}} onMouseDown={e=>{const inp=e.currentTarget.querySelector(INPUT_SEL);if(!inp||document.activeElement===inp)return;e.preventDefault();focusEnd(inp);setActiveDay?.(d);}}><input data-slot-input className="h-full w-full bg-transparent px-1 text-center text-[13px] font-bold text-white outline-none placeholder:text-white/22" autoComplete="off" spellCheck={false} value={val} onChange={e=>{const v=e.target.value;setSchedule?.(s=>!s?s:{...s,rows:(s.rows||[]).map(r=>((r.staffId??r.id??r.staff?.id)===(row.staffId??row.id??row.staff?.id))?{...r,[field]:v}:r)})}} onBlur={e=>saveCell?.((row.staffId??row.id??row.staff?.id),d,e.target.value)} onMouseDown={e=>{if(document.activeElement===e.currentTarget)e.stopPropagation()}} onFocus={e=>{focusEnd(e.target);setActiveDay?.(d)}} onKeyDown={e=>{const input=e.currentTarget,v=input.value||"",pos=input.selectionStart??v.length,rowEl=input.closest(ROW_SEL),table=tableRef?.current||rowEl?.parentElement;if(e.key==="ArrowLeft"&&pos===0&&d>1){e.preventDefault();const prev=rowEl?.querySelector(`${CELL_SEL}:nth-child(${d-1}) ${INPUT_SEL}`);if(prev){focusEnd(prev);setActiveDay?.(d-1)}}else if(e.key==="ArrowRight"&&pos===v.length&&d<daysInMonth){e.preventDefault();const next=rowEl?.querySelector(`${CELL_SEL}:nth-child(${d+1}) ${INPUT_SEL}`);if(next){focusEnd(next);setActiveDay?.(d+1)}}else if((e.key==="ArrowUp"||e.key==="ArrowDown"||e.key==="Enter")&&table&&rowEl){e.preventDefault();const rows=[...table.querySelectorAll(ROW_SEL)],ri=rows.indexOf(rowEl),ti=e.key==="ArrowUp"?ri-1:ri+1;if(ti<0||ti>=rows.length)return;const next=rows[ti]?.querySelector(`${CELL_SEL}:nth-child(${d}) ${INPUT_SEL}`);if(next){focusEnd(next);setActiveDay?.(d)}}}}/></div>})}{(statsLabels||[]).map((s,si)=><div key={`${rowId}-st-${si}`} className={`${statCell} box-border flex items-center justify-center rounded-[5px] px-1 text-[12px] font-black text-violet-50/92`} style={{height:ROW_H,width:STAT_W[si]||Math.round(DAY_W*1.1)}}>{stats?.[s]??"0"}</div>)}</div>;
},(a,b)=>a.row===b.row&&a.stats===b.stats&&a.days===b.days&&a.daysInMonth===b.daysInMonth&&a.gridTemplate===b.gridTemplate&&a.statsLabels===b.statsLabels);
export default function Schedule({days,daysInMonth,weekdayByDay,dcByDay,dcSorted,activeDay,setActiveDay,topRef,gridScrollRef,headScrollRef,namesRef,sortedRows,setSchedule,tableRef,saveCell,statsByStaffId,hScrollRef,hScrollW,statsLabels}){
  const safeDays=useMemo(()=>days?.length?days:Array.from({length:31},(_,i)=>i+1),[days]),gridTemplate=useMemo(()=>cols(safeDays,statsLabels||[]),[safeDays,statsLabels]);
  return <div className="flex w-full flex-col gap-2.5 overflow-hidden"><DayStrip days={safeDays} daysInMonth={daysInMonth} weekdayByDay={weekdayByDay} dcByDay={dcByDay} dcSorted={dcSorted} activeDay={activeDay} setActiveDay={setActiveDay} topRef={topRef}/><div className="flex flex-none flex-col overflow-hidden rounded-[9px] border border-cyan-400/35 bg-[#020813]"><HeaderGrid days={safeDays} daysInMonth={daysInMonth} activeDay={activeDay} setActiveDay={setActiveDay} headScrollRef={headScrollRef} statsLabels={statsLabels} gridTemplate={gridTemplate}/><div ref={gridScrollRef} className="overflow-auto [scrollbar-width:none] [&::-webkit-scrollbar]:hidden" style={{height:BODY_H,maxHeight:BODY_H,padding:PAD,contain:"layout paint"}}><div className="flex w-max items-start"><NameColumn sortedRows={sortedRows} namesRef={namesRef}/><div ref={tableRef} className="flex flex-col" style={{gap:GRID_GAP}}>{(sortedRows||[]).map((row,i)=><ScheduleRow key={rid(row)??`r-${i}`} row={row} index={i} days={safeDays} daysInMonth={daysInMonth} setActiveDay={setActiveDay} setSchedule={setSchedule} tableRef={tableRef} saveCell={saveCell} stats={statsByStaffId?.[String(rid(row)??`r-${i}`)]||EMPTY_STATS} statsLabels={statsLabels} gridTemplate={gridTemplate}/>)}</div></div></div></div><div className="shrink-0 rounded-[8px] border border-cyan-400/25 bg-[#020813] px-2 py-2"><div ref={hScrollRef} className="overflow-x-auto overflow-y-hidden rounded-full border border-white/8 bg-[#07111d] [scrollbar-color:rgba(56,189,248,.85)_rgba(2,6,23,.45)] [scrollbar-width:thin] [&::-webkit-scrollbar]:h-[12px] [&::-webkit-scrollbar-thumb]:rounded-full [&::-webkit-scrollbar-thumb]:border [&::-webkit-scrollbar-thumb]:border-cyan-400/45 [&::-webkit-scrollbar-thumb]:bg-sky-400/85 [&::-webkit-scrollbar-track]:rounded-full [&::-webkit-scrollbar-track]:border [&::-webkit-scrollbar-track]:border-white/10 [&::-webkit-scrollbar-track]:bg-[#07111d]"><div style={{width:`${hScrollW||1}px`,height:1}}/></div></div></div>;
}
