// components/Admin/Calendar/Calendar_Month.js
"use client";
import{useEffect}from"react";

export default function Calendar_Month({pickLabel,createOpen,closeCreate,createRef,createCode,setCreateCode,createErr,creating,submitCreate,monthOpen,setMonthOpen,monthYears,monthGroups,selected,setSelected,loadSchedule,openCreate,openCalc,openPicker}){
useEffect(()=>{if(createOpen)setTimeout(()=>createRef.current?.focus(),0)},[createOpen]);
return(<>{createOpen&&(<div className="create-box" onMouseDown={closeCreate}><div className="create-window" onMouseDown={e=>e.stopPropagation()}><button type="button" className="modal-x" onClick={closeCreate} aria-label="Close">×</button><h3>Създай График</h3><div className="create-label">Код за месец</div><input ref={createRef} className="create-input" value={createCode} onChange={e=>setCreateCode(e.target.value)} placeholder="Dec25" autoComplete="off"/>{!!createErr&&<div className="create-error">{createErr}</div>}<div className="create-actions"><button type="button" className="create-save" onClick={submitCreate} disabled={creating}>{creating?"...":"Създай"}</button></div></div></div>)}
{monthOpen&&(<div className="monthpick-box" onMouseDown={()=>setMonthOpen(false)}><div className="monthpick-window" onMouseDown={e=>e.stopPropagation()}><button type="button" className="modal-x" onClick={()=>setMonthOpen(false)} aria-label="Close">×</button><h3>Избери месец</h3>{!monthYears.length?(<div className="monthpick-empty">Няма графици</div>):(<div className="monthpick-years">{monthYears.map(y=>(<div key={y} className="monthpick-year"><div className="monthpick-year-title">{y}</div><div className="monthpick-grid">{(monthGroups.get(y)||[]).map(({code})=>(<button key={code} type="button" title={code} className={"monthpick-item"+(code===selected?" active":"")} onClick={()=>{setSelected(code);loadSchedule(code);setMonthOpen(false)}}>{code.slice(0,3)}</button>))}</div></div>))}</div>)}</div></div>)}
<div className="cal-top-bar"><button className="create-btn" onClick={openCreate}>Създай График</button><div className="month-wrap"><button type="button" className="month-select" onClick={()=>setMonthOpen(true)}>{selected}</button></div><button className="calc-btn" onClick={openCalc}>Изчисления</button><button className="add-croupier-btn" style={{marginTop:0}} onClick={openPicker}>Избери {pickLabel||"Служител"}</button></div>
</>);
}
